trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: docker build -t pinaki1/nodemoviebotapp:nodemoviebotapp . 
- script: docker login -u pinaki1 -p zaq1Xsw2@
- script: |
    docker login -u pinaki1 -p zaq1Xsw2@
    docker push pinaki1/nodemoviebotapp:nodemoviebotapp